name: Production Release

on:
  push:
    branches: ['main']
    tags: ['v*']

jobs:
  test:
    name: Run Tests
    type: generic
    steps:
      - run: bun install
      - run: bun run lint
      - run: bun run type-check
      - run: bun test -- --coverage

  build_android:
    name: Build Android Production
    type: build
    needs: test
    params:
      platform: android
      profile: production-store

  build_ios:
    name: Build iOS Production
    type: build
    needs: test
    params:
      platform: ios
      profile: production

  submit_android:
    name: Submit to Play Store
    type: submit
    needs: build_android
    params:
      platform: android

  submit_ios:
    name: Submit to App Store
    type: submit
    needs: build_ios
    params:
      platform: ios
