name: Production Build

on:
  push:
    branches: ['main']

jobs:
  build_android:
    name: Build Android
    type: build
    params:
      platform: android
      profile: production

  build_ios:
    name: Build iOS
    type: build
    params:
      platform: ios
      profile: production

  submit:
    name: Submit to Stores
    type: submit
    needs: [build_android, build_ios]
    params:
      android:
        track: production
      ios:
        ascAppId: ${{ vars.ASC_APP_ID }}
