-- Production rule: do not seed fabricated activity.
--
-- Trick definitions belong in the trick dictionary. Bounties must be created by
-- the real bounty workflow, and events must represent actual published events.
-- This migration intentionally contains no INSERTs so a fresh production setup
-- never receives fake bounties, fake activity, or pretend scheduled events.
