name: 'Auto Merge on Label'

on:
  pull_request_target:
    types: [labeled]

permissions:
  contents: write
  pull-requests: write

jobs:
  merge-on-auto-label:
    if: github.event.label.name == 'auto-merge'
    runs-on: ubuntu-latest
    steps:
      - name: Enable auto-merge for labeled PR
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ github.event.pull_request.number }}
          merge-method: squash
