name: Manual Build Trigger

on:
  workflow_dispatch:
    inputs:
      platform:
        description: Platform
        required: true
        default: android
        type: choice
        options: [android]
      profile:
        description: Profile
        required: true
        default: production
        type: choice
        options: [production, preview]

jobs:
  android-build:
    permissions:
      contents: read
    uses: ./.github/workflows/build-management.yml
    with:
      platform: android
      profile: ${{ github.event.inputs.profile }}
      auto_submit: false
      reason: manual-workflow-dispatch-android
    secrets: inherit
